136 moved call for help display functions to shared folder
TheAfroOfDoom/omega-flowey-minecraft-remastered pull request #154
Opened 2024-08-03 14:48 UTC by WesLSmith

Functions for summoning and terminating the call for help display have been moved into athe .../entity:soul/shared folder instead of being defined for each soul event

![image](https://github.com/user-attachments/assets/2f6971d9-346f-4d87-a6b3-dbce99c6389c)

Testing: Ran soul event to confirm new function locations still work 

creation 
![image](https://github.com/user-attachments/assets/6011b041-2e4c-4a91-b29f-1a6a93264214)

termination
![image](https://github.com/user-attachments/assets/ad430bd5-9ef0-4fff-850f-97772674ec9e)

2024-08-03 16:48 UTC, TheAfroOfDoom requested changes
looks good. one small thing:

can you add a initializing tag? `call-for-help-display-new` and add some initialize functions. we want each variant to have its own tag, like soul_5 summoning the display should give it the soul_5 tag as well, not soul_0 tag

2024-08-03 20:23 UTC, WesLSmith commented
instead of multiple init files what if we checked to see if there's a currently an active soul event then apply the tag based on which one exists?

2024-08-08 01:34 UTC, TheAfroOfDoom commented
> instead of multiple init files what if we checked to see if there's a currently an active soul event then apply the tag based on which one exists?
> 
> if there exists entity with tag soul 0 summon with tag soul 0 etc

this is a bleehh pattern. it'd work though.

go for it 🤷

2024-08-08 20:47 UTC, WesLSmith commented
> > instead of multiple init files what if we checked to see if there's a currently an active soul event then apply the tag based on which one exists?
> > if there exists entity with tag soul 0 summon with tag soul 0 etc
> 
> this is a bleehh pattern. it'd work though.
> 
> go for it 🤷

Wait educate me why is it a bad pattern? My instinct is to not have a bunch of similarly named functions but is there a reason we'd prefer having them?

2024-08-09 14:42 UTC, TheAfroOfDoom requested changes
there's actually a decent chance we can change this PR quite a bit to fully utilize the benefit of shared code. we can call on Discord sometime today for me to walk you through it

2024-08-11 03:35 UTC, WesLSmith commented
put init files with @s selector tag info into each soul event then have those init files call shared/summon

2024-08-18 01:55 UTC, TheAfroOfDoom requested changes

2024-08-18 01:55 UTC, TheAfroOfDoom commented on datapacks/omega-flowey/data/entity/function/soul/soul_0/call_for_help_display/initialize/initialize.mcfunction
> +execute as @s run function entity:soul/shared/call_for_help_display/summon
`execute as @s run` is a no-op

2024-08-18 02:00 UTC, WesLSmith commented on datapacks/omega-flowey/data/entity/function/soul/soul_0/call_for_help_display/initialize/initialize.mcfunction
> +execute as @s run function entity:soul/shared/call_for_help_display/summon
done!

2024-08-18 02:02 UTC, TheAfroOfDoom requested changes

2024-08-18 02:02 UTC, TheAfroOfDoom commented on datapacks/omega-flowey/data/entity/function/soul/soul_0/call_for_help_display/initialize/initialize.mcfunction
> +execute as @s run function entity:soul/shared/call_for_help_display/summon
i'm not seeing anything ever call `function entity:soul/soul_0/call_for_help_display/initialize`?

it doesn't make a lot of sense to call the summon function from within this initialize function.

the pattern we've been using for other parts is:

1. summon
2. `execute as @e[tag=...-new] run function initialize`
3. (in `initialize`) <initialize things>, `tag @s remove ...-new`

2024-08-18 02:02 UTC, TheAfroOfDoom commented on datapacks/omega-flowey/data/entity/function/soul/soul_0/call_for_help_display/initialize/initialize.mcfunction
> +execute as @s run function entity:soul/shared/call_for_help_display/summon
i can push a commit that makes these changes if you'd like. may be better to show rather than tell? up 2 you though, im not in a rush so feel free to take another crack at it if you want

2024-08-18 02:11 UTC, TheAfroOfDoom commented on datapacks/omega-flowey/data/entity/function/soul/soul_5/call_for_help_display/initialize.mcfunction
>  tag @s add soul_5
notice that if we didn't have this `tag @s add soul_5` command, the `call-for-help-display` (CFHD) wouldn't terminate at the end of the soul event.

you can test this easily by commenting out this line

2024-08-18 02:15 UTC, TheAfroOfDoom approved these changes
thx 4 ur patience 😸

2024-08-18 02:17 UTC, merged