Adds scripts that enable automated export of Animated Java files
TheAfroOfDoom/omega-flowey-minecraft-remastered pull request #64
Opened 2024-01-10 20:22 UTC by aidant19

# Summary

This PR addresses #8 and adds three files:

- bb-cli.js
- ajexport.js
- config.json

The **bb-cli.js** script must be loaded from file as a plugin within Blockbench and can then be used to execute scripts from the command line. Usage is as follows:

> blockbench.exe --bb-cli {path_to_script}

**NOTE**: Since the scripts are executed from the Blockbench directory, the script must either be moved to the BB directory or a full path must be provided.

The **ajexport.js** script is a script that automatically exports .ajmodel files indicated by a directory with the config.json file. The config file is also used to provide the target data pack and resource pack files, as well as locate the assets necessary for Animated Java / Blockbench export. These currently must be changed manually.

**NOTE**: Currently, the ajexport.js script requires a modified version of Animated Java that exposes the safeExportProject() function to the AJ API. A repository containing such a modification can be found here:
> https://github.com/aidant19/animated-java
---

## Test plan

Not currently planned at this stage.

## Reproducing in-game

N/A

## Preview

![ajexport](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/assets/12489538/38fd8702-ce4e-4882-bced-b5bcf293d5ac)

## Supplemental changes

- Changed .editorconfig to not enforce single quotations on json
- Specified prettier as default json formatter in workspace

2024-01-10 21:56 UTC, TheAfroOfDoom requested changes
lotta stuff as a start, mostly small things and pretty easy though.

have more stuff in the pipeline, but just focus on these for now

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/ajexport.js
> +    // TODO this should maybe be regex?
can delete this TODO prob

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/ajexport.js
> +      // });
no commented code 😡

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/ajexport.js
> +  return [resourcePackPath, dataPackPath, assetsPath, ajmodelPath];
this should return an object instead of an array since its so many elements

```suggestion
  return { resourcePackPath, dataPackPath, assetsPath, ajmodelPath };
```

this makes using its return value later much more readable and intuitive

e.g.

```ts
const resourcePackBase = paths[0].split('resourcepack')[0];
```
->
```ts
const resourcePackBase = paths.resourcePackPath.split('resourcepack')[0];
```

---

see bottom of this [stackoverflow answer](https://stackoverflow.com/a/2917186/13789724) for a little more reading on this

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/ajexport.js
> +  const f = JSON.parse(fs.readFileSync(configFile).toString());
rename this variable to be more descriptive pls

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/ajexport.js
> +  const f = JSON.parse(fs.readFileSync(configFile).toString());
ig `toString()` works on file data buffers. ive been using this tho
```suggestion
  const f = JSON.parse(fs.readFileSync(configFile, 'utf8'));
```

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/bb-cli.js
> +global BBPlugin, electron, window
was surprised `window` wasn't a global already. found this: https://eslint.org/docs/latest/use/configure/language-options#using-configuration-comments

so should be able to add `/* eslint-env browser */` to top of file for `window` to be properly detected as a global and not manually specified by us here

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/bb-cli.js
> +// With thanks to fetchbot on discord for the code
same feedback here as top of `ajexport.js` file (TODO link comment). pls be more specific/add links where possible

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/bb-cli.js
> +  description: 'Blockbench CLI plugin (in testing)',
```suggestion
  description: 'Blockbench CLI plugin',
```

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/bb-cli.js
> +    let [...ARGV] = electron.getGlobal('process').argv;
maybe we should add a check here to make sure the process is actually blockbench? maybe not though.

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/bb-cli.js
> +    let [...ARGV] = electron.getGlobal('process').argv;
dont love the variable name being `ARGV`; it could definitely just be `argv`

all-caps variables are generally for like, string/numeric file-wide constants.

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/bb-cli.js
> +    let [...ARGV] = electron.getGlobal('process').argv;
check out `run-linting-rules` / the `minimist` package it uses for how we have parsed CLI args previously

https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/blob/7fa7cf85e0c74b79f0c6c9357b9967ae9d781e45/package-scripts/run-linting-rules.js#L5

much cleaner and more readable than the slice/`indexOf` stuff we're doing below imo. worth converting to

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/bb-cli.js
> +      console.log(script);
this log seems unnecessary

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/bb-cli.js
> +          //window.close();
delete this pls

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/config.json
> +  "ajmodel_folder": "C:\\Users\\Aidan\\Documents\\Media_Storage\\active_projects\\flowey_remaster\\test\\resourcepack\\assets\\omega-flowey\\models\\entity\\hostile\\omega-flowey"
i think i pretty strongly prefer `camelCase` for json/JS variable names. Minecraft uses `snake_case` for its stuff, but for our external scripts/tooling lets stick to `camelCase`

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/bb-cli.js
> +    let [...ARGV] = electron.getGlobal('process').argv;
may run into issues if blockbench doesnt already have `minimist` as a package? unsure if itll fallback to our yarn's `minimist` or what

2024-01-10 21:56 UTC, TheAfroOfDoom commented on scripts/config.json
we should move these files in `scripts` into `package-scripts`

2024-01-10 22:40 UTC, aidant19 commented on .editorconfig
> -indent_style = space
[bc16125](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/bc16125fd7cc19f8ac7380e99cec2156a0af2872)

2024-01-10 23:23 UTC, aidant19 commented on omega-flowey.code-workspace
> -
[4d1441b](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/4d1441b8e60dcde06a2d40059bf79142f0d8a8c5)

2024-01-10 23:23 UTC, aidant19 commented on omega-flowey.code-workspace
> +    "[json]": {
[4d1441b](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/4d1441b8e60dcde06a2d40059bf79142f0d8a8c5)

2024-01-10 23:31 UTC, aidant19 commented on scripts/ajexport.js
> +// With thanks to elenterius on discord for troubleshooting ideas
[d057bcb](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/d057bcba909c3b344b6c75b242729b04056376dc)

The actual contribution was essentially overwritten in bb-cli, but it got us there and I like giving little shoutouts when possible

2024-01-10 23:34 UTC, aidant19 commented on scripts/ajexport.js
> +global Project, fs, loadModelFile, AnimatedJava
[573d8de](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/573d8dec2d5efd4229a5c67ee1078eb141d34bcb)

2024-01-10 23:38 UTC, aidant19 commented on scripts/ajexport.js
> +console.log('Target paths: ', paths);
I'd like to keep this because it is handy for debugging

2024-01-10 23:39 UTC, aidant19 commented on scripts/ajexport.js
> +*/
They may be useful in the future but I am okay with deleting to keep file clean

2024-01-10 23:40 UTC, aidant19 commented on scripts/ajexport.js
> +*/
[a942895](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/a9428953eee63385527c5e247c14e2c08af8cfa3)

2024-01-10 23:41 UTC, aidant19 commented on scripts/ajexport.js
> +    // TODO this should maybe be regex?
[c258a75](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/c258a753b0badd1184efbe24cb51cb4505f9d2eb)

2024-01-10 23:42 UTC, aidant19 commented on scripts/ajexport.js
> +      // });
coming at me with angry face over code you wrote smh

2024-01-10 23:43 UTC, aidant19 commented on scripts/ajexport.js
> +      // });
[0052d8b](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/0052d8b58fef02b6c87f75b227ed0cff202deeab)

2024-01-10 23:59 UTC, aidant19 commented on scripts/ajexport.js
> +  return [resourcePackPath, dataPackPath, assetsPath, ajmodelPath];
[2e52c93](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/2e52c938be114dd3773a6a778bd805e0bc3fb2a8)

2024-01-11 00:01 UTC, aidant19 commented on scripts/ajexport.js
> +  const f = JSON.parse(fs.readFileSync(configFile).toString());
[6b67a86](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/6b67a86876182800b244ca0eee985f8879dc30a4)

2024-01-11 00:03 UTC, aidant19 commented on scripts/ajexport.js
> +  const f = JSON.parse(fs.readFileSync(configFile).toString());
[6efb816](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/6efb816e56200daf9da8b351c005286820d4eb3d)

2024-01-11 00:04 UTC, aidant19 commented on scripts/ajexport.js
> +  let resourcePackPath = f.resource_pack_mcmeta;
[0d039ab](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/0d039ab809f91ad0590611a88b5fbeb15b5f5a20)

and 

[3cc0b74](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/3cc0b74b4b76ed76ec019b64b8d3bb1401c5515e)

2024-01-11 00:06 UTC, aidant19 commented on scripts/bb-cli.js
> +global BBPlugin, electron, window
[0aa311b](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/0aa311b6d016695cf8b53df1682fc664edb1a594)

2024-01-11 00:07 UTC, aidant19 commented on scripts/bb-cli.js
> +// With thanks to fetchbot on discord for the code
[0916b63](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/0916b631f2fdceac6277f5f4ddfd74264d8e5325)

2024-01-11 01:05 UTC, TheAfroOfDoom commented on scripts/ajexport.js
> +*/
> They may be useful in the future but I am okay with deleting to keep file clean

they will exist here in the PR for later reference if needed

2024-01-11 17:26 UTC, aidant19 commented on scripts/bb-cli.js
> +    let [...ARGV] = electron.getGlobal('process').argv;
[834c57c](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/834c57cdfdc08cdeb8305f498fd32dc36ed410d6)

2024-01-11 17:28 UTC, aidant19 commented on scripts/bb-cli.js
> +      console.log(script);
[88c1b2c](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/88c1b2c9f6d9878383943a782027e858d2f88c61)

2024-01-11 17:32 UTC, aidant19 commented on scripts/config.json
> +  "ajmodel_folder": "C:\\Users\\Aidan\\Documents\\Media_Storage\\active_projects\\flowey_remaster\\test\\resourcepack\\assets\\omega-flowey\\models\\entity\\hostile\\omega-flowey"
[457a948](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/457a948b38779a0d02e8452f256cc6cbc00dfc59)

2024-01-11 17:55 UTC, aidant19 commented on scripts/bb-cli.js
> +    let [...ARGV] = electron.getGlobal('process').argv;
`minimist` does not appear to be imported by bb, I think it may not be a bad idea to consider this a future TODO

2024-01-11 18:33 UTC, aidant19 commented on scripts/bb-cli.js
> +          //window.close();
[e33b123](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/e33b1236570e1b9d685f0c517fe57e1289c16d45)

2024-01-11 20:14 UTC, aidant19 commented on scripts/bb-cli.js
> +    let [...ARGV] = electron.getGlobal('process').argv;
TODO candidate

2024-01-11 20:20 UTC, aidant19 commented on scripts/config.json
[b2cb11b](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/b2cb11b6b039f16d89d48503d09bfdfa68cdff95)

2024-01-11 20:20 UTC, aidant19 commented on scripts/ajexport.js
> +const paths = getConfigPaths(
[72e48f8](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/72e48f8968e550e43d11e2768938929b4e820d41)

2024-01-11 20:30 UTC, aidant19 commented on scripts/bb-cli.js
> +    let [...ARGV] = electron.getGlobal('process').argv;
https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/issues/65

2024-01-11 20:33 UTC, aidant19 commented on scripts/bb-cli.js
> +    let [...ARGV] = electron.getGlobal('process').argv;
https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/issues/66

2024-01-11 20:43 UTC, aidant19 commented on scripts/ajexport.js
> +  let resourcePackPath = f.resource_pack_mcmeta;
[eb20519](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/eb20519fdc9a943d532956796b9aca74e86c4926)

2024-01-11 20:49 UTC, aidant19 commented
Requested changes made to PR. Does not significantly alter functionality, but significant improvements made to formatting consistency, readability, and code integrity.

Of note:
ajexport.js now exports its main code as an async function and is able to await each export. bb-cli is now able to properly await its conclusion and then exit.

New supplemental changes:
- scripts now exist in package-scripts/modules
- eslint enforces const requirement

2024-01-11 21:37 UTC, TheAfroOfDoom commented on scripts/ajexport.js
> +// With thanks to elenterius on discord for troubleshooting ideas
makes sense

2024-01-11 22:16 UTC, TheAfroOfDoom requested changes
a few more small things relating to the code quality/style.

let's also add to the `README.md` setup section how to configure e.g. `config.json`, load the bb-cli plugin into Blockbench, and run the script.

---

can we also add labels to the new tickets? #65 and #66 

they're both `devops` and `enhancement` imo

2024-01-11 22:16 UTC, TheAfroOfDoom commented on package-scripts/modules/bb-cli.js
> +    }
this should close the window even if it errors i think. ideally also print the error in the terminal through which you ran the script. you can probably add a [finally block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally) after the catch to put `window.close()` in?

2024-01-11 22:16 UTC, TheAfroOfDoom commented on package-scripts/modules/ajexport.js
> +    file.includes('ajmodel'),
```suggestion
    file.endsWith('.ajmodel'),
```

effectively same behavior, slightly more correct + readable

technically fixes a bug if we happened to have `ajmodel.txt` as a file which would pass and break the script (assuming it wasn't a real model file)

2024-01-11 22:16 UTC, TheAfroOfDoom commented on package-scripts/modules/ajexport.js
> +  const files = readdirSync(modelDir).filter((file) =>
this doesn't search recursively yet right? can we fix that?

i found https://stackoverflow.com/a/45130990/13789724

> As of Node 20, `fs.readdir` has a `{ recursive: true }` option

so maybe

```suggestion
  const files = readdirSync(modelDir, { recursive: true }).filter((file) =>
```

it worked for me locally so 🤞

2024-01-11 22:16 UTC, TheAfroOfDoom commented on package-scripts/modules/ajexport.js
> +      name: name,
```suggestion
      name,
```

pls add `object-shorthand: 'error'` to `.eslintrc.yml`

https://eslint.org/docs/latest/rules/object-shorthand

2024-01-11 22:16 UTC, TheAfroOfDoom commented on package-scripts/modules/ajexport.js
> +      const x = texture.path.split('resourcepack/assets')[1];
can we think of more descriptive names for these `x` variables?

2024-01-12 00:48 UTC, aidant19 commented on package-scripts/modules/ajexport.js
> +      name: name,
[4942163](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/494216318489e524138553ed6562a2fe26133593)
and
[c6c9996](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/c6c9996306c1d061b505ef06ed6b5918e01e1fc2)

2024-01-12 00:48 UTC, aidant19 commented on package-scripts/modules/ajexport.js
> +      const x = texture.path.split('resourcepack/assets')[1];
[0055e40](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/0055e405fb036f948b5d8c2f008eb6b77e4896c0)

2024-01-12 01:28 UTC, aidant19 commented on package-scripts/modules/config.json
> +}
[482f476](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/482f47662e941997bf891de7f46f8a7dc9424aac)

2024-01-12 01:29 UTC, aidant19 commented on package-scripts/modules/ajexport.js
> +}
[482f476](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/482f47662e941997bf891de7f46f8a7dc9424aac)

2024-01-12 01:29 UTC, aidant19 commented on package-scripts/modules/bb-cli.js
> +    const [...argv] = electron.getGlobal('process').argv;
[0c7c4ab](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/0c7c4ab30fee5a9582cdeedb6f33f371021eb966)

2024-01-12 01:29 UTC, aidant19 commented on package-scripts/modules/bb-cli.js
> +    }
[1adeae5](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/1adeae5f56f2cfeb21e8ce3fa8b89b831673b305)

2024-01-12 01:30 UTC, aidant19 commented on package-scripts/modules/bb-cli.js
> +    }
Tabled for now - working with cmd line and bb simultaneously may be involved

2024-01-12 01:31 UTC, aidant19 commented on package-scripts/modules/ajexport.js
> +  const files = readdirSync(modelDir).filter((file) =>
[66260ab](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/64/commits/66260abeb0cf717d69ae8b104d8e2485f2958761)

Implemented and then reverted

2024-01-12 01:31 UTC, aidant19 commented on package-scripts/modules/ajexport.js
> +  const files = readdirSync(modelDir).filter((file) =>
For now

2024-01-17 01:05 UTC, aidant19 commented
LGTM and works locally

2024-01-17 03:11 UTC, TheAfroOfDoom approved these changes
LGTM thx for rebasing correctly

2024-01-17 03:22 UTC, merged